<a href="https://colab.research.google.com/github/Thakur9723/DATA-SCIENCE-ASSINGMENTS/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import libraries
!pip install tensorflow
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [5]:
#load the data

In [8]:
df=pd.read_csv('/Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [10]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [11]:
df=pd.get_dummies(data=df,columns=['Geography','Gender'])
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

model bulding

In [12]:
sc=StandardScaler()
x=df.drop(columns=['Exited'])
y=df['Exited']

In [13]:
x=sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [20]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
#initialise model
ann=Sequential()
#add hiden layer
ann.add(Dense(units=10,activation='relu'))
#add output layer
ann.add(Dense(units=1,activation='sigmoid'))
#establish the connection between the layer
ann.compile(optimizer='adadelta',loss='binary_crossentropy',metrics='accuracy')
#fit the data
ann.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.7022 - accuracy: 0.5405
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7013 - accuracy: 0.5422
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7003 - accuracy: 0.5426
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6992 - accuracy: 0.5440
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6982 - accuracy: 0.5460
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6971 - accuracy: 0.5472
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6960 - accuracy: 0.5489
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6950 - accuracy: 0.5502
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.5519
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6928 - accura

In [22]:
ypred=ann.predict(xtest)
ypred

63/63 [==============================] - 0s 2ms/step


array([[0.5776066 ],
       [0.24145004],
       [0.444142  ],
       ...,
       [0.28035128],
       [0.35695   ],
       [0.5071646 ]], dtype=float32)

In [23]:
ypred>0.5

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [24]:
ypred=ypred>0.5
ypred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [25]:
ytest

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [26]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.83      0.74      0.78      1607
           1       0.26      0.38      0.31       393

    accuracy                           0.67      2000
   macro avg       0.55      0.56      0.55      2000
weighted avg       0.72      0.67      0.69      2000



In [27]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

Hyperparameter tuning

In [32]:
!pip install -U keras-tuner


Tunning the ann model

In [34]:
import keras_tuner as kt

In [52]:
def optimizer_selection(hp):
  model = Sequential()
#add hiden layer
  model.add(Dense(units=10,activation='relu'))
#add outeput layer
  model.add(Dense(units=1,activation='sigmoid'))
#optimizer selection
  optime=hp.Choice('optimizer',values=['sgd','adam','rmsprop'])
  model.compile(optimizer=optime,loss='binary_crossentropy',metrics='accuracy')
  return model

In [53]:
tuner=kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

Reloading Tuner from ./untitled_project/tuner0.json


In [54]:
tuner.search(xtrain,ytrain, epochs=3,validation_data=(xtest,ytest))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8184999823570251

Best val_accuracy So Far: 0.8184999823570251
Total elapsed time: 00h 02m 49s


In [56]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [57]:
model=tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain,epochs=100,validation_data=(xtest,ytest))

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.4261 - accuracy: 0.8149 - val_loss: 0.4069 - val_accuracy: 0.8195
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4171 - accuracy: 0.8202 - val_loss: 0.3987 - val_accuracy: 0.8270
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4089 - accuracy: 0.8259 - val_loss: 0.3907 - val_accuracy: 0.8305
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4012 - accuracy: 0.8304 - val_loss: 0.3838 - val_accuracy: 0.8340
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3932 - accuracy: 0.8353 - val_loss: 0.3769 - val_accuracy: 0.8420
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3854 - accuracy: 0.8401 - val_loss: 0.3707 - val_accuracy: 0.8450
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3785 - accuracy: 0.8438 - val_loss: 0.3658 - val_accuracy: 0.8490